# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .playlist import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "youtubeplaylist-native",
  "mod": "index",
  "fqn": "pulumi_youtubeplaylist_native",
  "classes": {
   "youtubeplaylist-native:index:Playlist": "Playlist"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "youtubeplaylist-native",
  "token": "pulumi:providers:youtubeplaylist-native",
  "fqn": "pulumi_youtubeplaylist_native",
  "class": "Provider"
 }
]
"""
)
