// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Playlist extends pulumi.CustomResource {
    /**
     * Get an existing Playlist resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Playlist {
        return new Playlist(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'youtubeplaylist-native:index:Playlist';

    /**
     * Returns true if the given object is an instance of Playlist.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Playlist {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Playlist.__pulumiType;
    }

    public readonly description!: pulumi.Output<string | undefined>;
    public readonly itemIds!: pulumi.Output<string[]>;
    public readonly playlistId!: pulumi.Output<string | undefined>;
    public readonly title!: pulumi.Output<string | undefined>;

    /**
     * Create a Playlist resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PlaylistArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.itemIds === undefined) && !opts.urn) {
                throw new Error("Missing required property 'itemIds'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["itemIds"] = args ? args.itemIds : undefined;
            resourceInputs["playlistId"] = args ? args.playlistId : undefined;
            resourceInputs["title"] = args ? args.title : undefined;
        } else {
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["itemIds"] = undefined /*out*/;
            resourceInputs["playlistId"] = undefined /*out*/;
            resourceInputs["title"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Playlist.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Playlist resource.
 */
export interface PlaylistArgs {
    description?: pulumi.Input<string>;
    itemIds: pulumi.Input<pulumi.Input<string>[]>;
    playlistId?: pulumi.Input<string>;
    title?: pulumi.Input<string>;
}
